### ISSUE TITLE
AUTHORIZATION_FAILURE with my MKR WiFi 1010 

### ISSUE THREAD

**Issue by ghost** [chariotsolutions/mkr_1010_iot_template#1]
Hi everyone, I followed the procedure in the readme to connect the arduino to aws iot core but I'm having connection problems with the MQTT broker. In fact, in the cloud watch logs I have an authorization error: AUTHORIZATION_FAILURE. Has anyone had similar problems? In the secrets folder I have the certificate.pem.crt file downloaded from iot, the .csr file and the file containing the secrets.

**Comment by aiacovella** [comment]
Start by checking the SECRET_BROKER value in the arduino_secrets.h file. Be sure that the correct broker is configured. Also, the SECRET_CERTIFICATE value is very finicky. You can not have any extra spaces invisible characters etc in there. It should also include the lines containing BEGIN CERTIFICATE and END CERTIFICATE in there so it should look something like the following with your cert in there instead fo the X's:


const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
-----END CERTIFICATE-----
)";


Was this file edited on a Windows machine or OSX/Linux ? 
Run the following command on OSX / Linux:

**cat -v arduino_secrets.h** 

and make sure you don't see **^M** appear in your certificate value. 






Also, can you post the full message for the authorization error you are seeing.

**Comment by ghost** [comment]
Hello, thank you for the reply. I have an OSx machine, I checked all the secrets.h file values and they are correct, both MQTT broker and certificate. I also checked for the absence of the **^M** character with **cat -v arduino_secrets.h**. Here is the complete log provided by cloud watch :

{
     "timestamp": "2023-03-03 21:02:50.901",
     "logLevel": "ERROR",
     "traceId": "",
     "accountId": "",
     "status": "Failure",
     "eventType": "Connect",
     "protocol": "MQTT",
     "clientId": "Arduino-0002cc4b",
     "principalId": "",
     "sourceIp": "",
     "sourcePort": ,
     "reason": "AUTHORIZATION_FAILURE",
     "details": "Authorization Failure"
}

I just can't figure out where the problem is.

**Comment by aiacovella** [comment]
Ok, this might be a policy issue. I've run through the directions (and updated some of course) and it seemed to work for me. Can you please review [this page](https://docs.aws.amazon.com/iot/latest/developerguide/diagnosing-connectivity-issues.html) and verify the items documented and let me know if that works for you? Thanks.

**Comment by ghost** [comment]
Hi actually reviewing the AWS documentation I noticed an error in writing the policy associated with the certificate. It allowed all actions but on the specific resource, changing the **"Resource"** field with **"*"** obviously solved the problem. I focused on the certificate because I thought it was a format problem but in reality the cause was much more simpler. Anyway, thank you for your availability. We can therefore consider the issue closed. Thanks again!

**Comment by aiacovella** [comment]
Great, Just remember that you would want more restrictive policies in a real world situation.

**Comment by aiacovella** [comment]
Resolved
